### PR TITLE
🌐 OOCv1 with Shadowsocks

### PR DESCRIPTION
**Pull request by database64128**
TODOs for @mzz2017:
1. Emit warnings for unsupported protocols and Shadowsocks servers with plugins.

### CODE REVIEW

**Comment by database64128** [comment]
This PR is ready for review. I'll add support for self-signed certificates at a later time.

**Comment by database64128** [comment]
I removed the timeout assignment because 30 seconds is the default. :P

**Comment by mzz2017** [comment]
@database64128 Why remove it, I think 30s is enough for fetching the response.

**Comment by mzz2017** [comment]
I have merge it manually. Thanks for your contributions! The OOCv1 is so brilliant!

**Pull request closed without merging**
