### PR TITLE
replace crypto/tls by uTLS

### PR DESCRIPTION
**Pull request by lilendian0x00**

### CODE REVIEW

**Comment by mzz2017** [comment]
@lilendian0x00 tls in utls is a strange and obvious characteristic. I do not suggest it.

**Comment by lilendian0x00** [comment]
> @lilendian0x00 tls in utls is a strange and obvious characteristic. I do not suggest it.

but it can bypass Iran's firewall! without uTLS it doesn't work

**Comment by lilendian0x00** [comment]
> @lilendian0x00 tls in utls is a strange and obvious characteristic. I do not suggest it.

uTLS is open source, isn't it?

**Comment by mzz2017** [comment]
@lilendian0x00 The plugin/tls is not work everywhere. If you want to apply it to all protocols, you should not modify this simply.

**Comment by lilendian0x00** [comment]
> @lilendian0x00 The plugin/tls does not work everywhere. If you want to apply it to all protocols, you should not modify this simply.

Sadly you are right ;( but at least there must be some where which folks can get v2rayA with uTLS option otherwise there is no way to bypass firewalls that does TLS fingerprinting

**Pull request closed without merging**
