### PR TITLE
Snapcraft version of v2rayA

### PR DESCRIPTION
**Pull request by InvisibleRain**
The build script is included with the PR. To build the snap yourself, just run
```
./snap.sh 1.5.8.1
```

To install the freshly-built snap, run
```
snap install --dangerous --jailmode ./v2raya_1.5.8.1_amd64.snap
```
(omit the `--jailmode` flag on non-Ubuntu systems)

Then give it all the required  permissions, and start:
```
./start-snap.sh
```

The `start-snap.sh` script is only needed when installing from a `.snap` file for development/testing purposes. The end user wishing to install v2rayA from snapcraft.io doesn't have to paste all these commands. A simple `snap install v2raya` would work just fine when the snap is released to snapcraft. Also, this snap will enable one-click installs from Gnome Software or Discover for non-power Linux users

### CODE REVIEW

**Comment by InvisibleRain** [comment]
The daemon status can be viewed and altered via:
```
snap services
sudo snap stop v2raya
sudo snap start v2raya
```

**Comment by MarksonHon** [comment]
Thanks for your work. However, can we pull this snap package to Ubuntu Snapcraft after building a new release by GitHub action?

**Comment by mzz2017** [comment]
@InvisibleRain Sounds good. And can you join us and maintain the snap?

**Comment by mzz2017** [comment]
@InvisibleRain I have no idea whether it is better that we create a new repo for it like what v2rayA/v2raya-copr do.

**Comment by InvisibleRain** [comment]
Well, yes, it's probably would be better to move all the snapcraft stuff into a separate repo. I'm ready to maintain it as far as my free time allows.

Pushing this snap to Ubuntu Snapcraft via means of GitHub Actions sounds possible. However, first we need to decide on the name of the snap. The simple "v2raya" is already registered by someone, but we can open up a dispute on the [snapcraft dashboard](https://dashboard.snapcraft.io/register-snap/). If this turns out too difficult, I already reserved a few names, such as v2raya-client and v2raya-proxy. In my opinion, it would be easier to argue on the dispute when v2raya/v2raya-snap repo will be published

**Comment by mzz2017** [comment]
@InvisibleRain It is a pretty good news to us. Welcome! I'll send an invition to your email now. And your plan looks acceptable.

**Comment by mzz2017** [comment]
@InvisibleRain We can try to open up a dispute first. And if it fails we can figure out if it is case sensitive so we can use v2rayA. Or another name should be discussed.

**Comment by InvisibleRain** [comment]
I created the repo and filed a dispute for the name at snapcraft.io 

Gonna wait and see what Canonical says

**Comment by mzz2017** [comment]
@InvisibleRain Cool! Let's wait for it.

**Comment by InvisibleRain** [comment]
Closing this pull request as there hasn't been any response from @CanonicalLtd on https://forum.snapcraft.io/t/auto-connection-request-for-v2raya/31100 for weeks.

You can still try and install the snap from https://snapcraft.io/v2raya. However, keep in mind that this is just a preview version. In order to use transparent proxy, you have to run
```
snap connect v2raya:firewall-control
snap connect v2raya:network-control
```

**Pull request closed without merging**
