### PR TITLE
fix: capture full output of v2ray

### LINKED ISSUE #770: v2ray应该已经安装了v5版本，但是v2raya仍然提示并非v5
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
2.0.1
2. 你通过什么方式安装v2rayA
github下载 然后使用pacman -U安装
3. 你所使用的操作系统
steamos3 基于archlinux

### 描述问题：
v2ray使用 pacman -S v2ray 安装
warning: v2ray-5.1.0-2 is up to date -- reinstalling

v2ray应该已经安装了v5版本，但是v2raya仍然提示：“检测到 v2ray-core 的版本并非 v5，请使用 v5 版本或将 v2rayA 降级至 v1.5”，试过重启但是没有用。

### v2rayA运行日志（Optional）：

```shell
2022/12/10 13:50:38.312 [E] [account.go:31] wrong username or password
2022/12/10 13:50:50.938 [E] [account.go:31] wrong username or password
2022/12/10 13:51:00.468 [E] [account.go:31] wrong username or password
2022/12/10 13:59:56.946 [I] [gfwlist.go:112] Downloading https://hubmirror.v2raya.org/v2rayA/dist-v2ray-rules-dat/raw/202212062210/geosite.dat to /root/.local/share/v2ray/LoyalsoldierSite.dat.new
2022/12/10 14:00:11.956 [I] [gfwlist.go:155] download[1]: https://hubmirror.v2raya.org/v2rayA/dist-v2ray-rules-dat/raw/202212062210/geosite.dat -> SUCCESS
2022/12/11 14:17:16.167 [A] [main.go:27] V2Ray binary is /usr/bin/v2ray
2022/12/11 14:17:16.167 [A] [main.go:27] V2Ray asset directory is /run/user/0/v2raya
2022/12/11 14:17:16.168 [A] [main.go:27] v2rayA working directory is /
2022/12/11 14:17:16.168 [A] [main.go:27] v2rayA configuration directory is /etc/v2raya
2022/12/11 14:17:16.168 [A] [main.go:27] Golang: go1.18.4
2022/12/11 14:17:16.168 [A] [main.go:27] OS: linux
2022/12/11 14:17:16.168 [A] [main.go:27] Arch: amd64
2022/12/11 14:17:16.168 [A] [main.go:27] Lite: false
2022/12/11 14:17:16.168 [A] [main.go:27] Version: 1.5.9.1698.1
2022/12/11 14:17:16.168 [A] [main.go:27] Starting...
2022/12/11 14:17:16.171 [W] [asm_amd64.s:1571] Failed to update PAC file: failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 127.0.0.53:53: server misbehaving
2022/12/11 14:17:16.179 [I] [main.go:28] the core was not running the last time v2rayA exited
2022/12/11 14:17:16.187 [W] [pre.go:272] UpdateSubscription: Get "": dial  on 127.0.0.53:53: server misbehaving: []
2022/12/11 14:17:16.187 [I] [asm_amd64.s:1571] [AutoUpdate] Subscriptions: Failed to update subscription -- ID: 0，err: UpdateSubscription: failed to resolve subscription address: Get " on 127.0.0.53:53: server misbehaving
2022/12/11 14:17:16.187 [A] [index.go:117] v2rayA is listening at http://127.0.0.1:2017
2022/12/11 14:17:16.187 [A] [index.go:117] v2rayA is listening at http://[::1]:2017
2022/12/13 23:47:11.344 [A] [main.go:27] V2Ray binary is /usr/bin/v2ray
2022/12/13 23:47:11.344 [A] [main.go:27] V2Ray asset directory is /run/user/0/v2raya
2022/12/13 23:47:11.344 [A] [main.go:27] v2rayA working directory is /
2022/12/13 23:47:11.344 [A] [main.go:27] v2rayA configuration directory is /etc/v2raya
2022/12/13 23:47:11.344 [A] [main.go:27] Golang: go1.18.4
2022/12/13 23:47:11.344 [A] [main.go:27] OS: linux
2022/12/13 23:47:11.344 [A] [main.go:27] Arch: amd64
2022/12/13 23:47:11.344 [A] [main.go:27] Lite: false
2022/12/13 23:47:11.344 [A] [main.go:27] Version: 1.5.9.1698.1
2022/12/13 23:47:11.344 [A] [main.go:27] Starting...
2022/12/13 23:47:11.346 [W] [asm_amd64.s:1571] Failed to update PAC file: failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 127.0.0.53:53: server misbehaving
2022/12/13 23:47:11.349 [I] [main.go:28] the core was not running the last time v2rayA exited
2022/12/13 23:47:11.353 [A] [index.go:117] v2rayA is listening at http://127.0.0.1:2017
2022/12/13 23:47:11.353 [A] [index.go:117] v2rayA is listening at http://[::1]:2017
2022/12/13 23:47:11.354 [W] [pre.go:272] UpdateSubscription: Get "on 127.0.0.53:53: server misbehaving: []
2022/12/13 23:47:11.354 [I] [asm_amd64.s:1571] [AutoUpdate] Subscriptions: Failed to update subscription -- ID: 0，err: UpdateSubscription: failed to resolve subscription address: Gon 127.0.0.53:53: server misbehaving
2022/12/14 17:49:50.146 [A] [main.go:27] V2Ray binary is /usr/bin/v2ray
2022/12/14 17:49:50.146 [A] [main.go:27] V2Ray asset directory is /run/user/0/v2raya
2022/12/14 17:49:50.146 [A] [main.go:27] v2rayA working directory is /
2022/12/14 17:49:50.146 [A] [main.go:27] v2rayA configuration directory is /etc/v2raya
2022/12/14 17:49:50.146 [A] [main.go:27] Golang: go1.18.4
2022/12/14 17:49:50.146 [A] [main.go:27] OS: linux
2022/12/14 17:49:50.146 [A] [main.go:27] Arch: amd64
2022/12/14 17:49:50.146 [A] [main.go:27] Lite: false
2022/12/14 17:49:50.146 [A] [main.go:27] Version: 1.5.9.1698.1
2022/12/14 17:49:50.146 [A] [main.go:27] Starting...
2022/12/14 17:49:50.149 [W] [asm_amd64.s:1571] Failed to update PAC file: failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 127.0.0.53:53: server misbehaving
2022/12/14 17:49:50.151 [I] [main.go:28] the core was not running the last time v2rayA exited
2022/12/14 17:49:50.156 [W] [pre.go:272] UpdateSubscription: Get "hon 127.0.0.53:53: server misbehaving: []
2022/12/14 17:49:50.156 [I] [asm_amd64.s:1571] [AutoUpdate] Subscriptions: Failed to update subscription -- ID: 0，err: UpdateSubscription: failed to resolve subscription address: Get 27.0.0.53:53: server misbehaving
2022/12/14 17:49:50.157 [A] [index.go:117] v2rayA is listening at http://127.0.0.1:2017
2022/12/14 17:49:50.157 [A] [index.go:117] v2rayA is listening at http://[::1]:2017
2022/12/31 17:56:57.848 [W] [main.go:24] Migrating from v4 to feat_v5
2022/12/31 17:56:57.903 [I] [main.go:24] Importing subscriptio
2022/12/31 17:56:57.906 [W] [main.go:24] Migration is done
2022/12/31 17:56:57.907 [A] [main.go:26] V2Ray binary is
2022/12/31 17:56:57.907 [A] [main.go:26] V2Ray asset directory is /run/user/0/v2raya
2022/12/31 17:56:57.907 [A] [main.go:26] v2rayA working directory is /
2022/12/31 17:56:57.907 [A] [main.go:26] v2rayA configuration directory is /etc/v2raya
2022/12/31 17:56:57.907 [A] [main.go:26] Golang: go1.19.3
2022/12/31 17:56:57.907 [A] [main.go:26] OS: linux
2022/12/31 17:56:57.907 [A] [main.go:26] Arch: amd64
2022/12/31 17:56:57.907 [A] [main.go:26] Lite: false
2022/12/31 17:56:57.907 [A] [main.go:26] Version: 2.0.1
2022/12/31 17:56:57.907 [A] [main.go:26] Starting...
2022/12/31 17:56:57.907 [I] [main.go:27] the core was not running the last time v2rayA exited
2022/12/31 17:56:57.910 [W] [asm_amd64.s:1594] Failed to update PAC file: failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 127.0.0.53:53: server misbehaving
2022/12/31 17:56:57.978 [A] [index.go:116] v2rayA is listening at http://127.0.0.1:2017
2022/12/31 17:56:57.978 [A] [index.go:116] v2rayA is listening at http://[::1]:2017
2022/12/31 18:00:31.418 [E] [account.go:31] wrong username or password
2022/12/31 18:00:40.638 [E] [account.go:31] wrong username or password
2022/12/31 18:00:44.013 [E] [account.go:31] wrong username or password
2022/12/31 18:00:51.901 [E] [account.go:31] wrong username or password
2022/12/31 18:08:46.769 [A] [main.go:24] downloading missing geoip.dat and geosite.dat
2022/12/31 18:08:46.769 [I] [geoip.go:16] Downloading https://hubmirror.v2raya.org/v2fly/geoip/releases/latest/download/geoip.dat to /root/.local/share/v2ray/geoip.dat.new
2022/12/31 18:09:38.363 [I] [pre.go:187] download[geoip.dat]: SUCCESS
2022/12/31 18:09:38.376 [I] [geosite.go:17] Downloading https://hubmirror.v2raya.org/v2fly/domain-list-community/releases/latest/download/dlc.dat to /root/.local/share/v2ray/geosite.dat.new
2022/12/31 18:09:47.509 [I] [pre.go:193] download[geosite.dat]: SUCCESS
2022/12/31 18:09:47.509 [A] [main.go:24] geoip.dat and geosite.dat are ready
2022/12/31 18:09:47.510 [A] [main.go:26] V2Ray binary is /usr/bin/v2ray
2022/12/31 18:09:47.510 [A] [main.go:26] V2Ray asset directory is /run/user/0/v2raya
2022/12/31 18:09:47.510 [A] [main.go:26] v2rayA working directory is /
2022/12/31 18:09:47.510 [A] [main.go:26] v2rayA configuration directory is /etc/v2raya
2022/12/31 18:09:47.510 [A] [main.go:26] Golang: go1.19.3
2022/12/31 18:09:47.510 [A] [main.go:26] OS: linux
2022/12/31 18:09:47.510 [A] [main.go:26] Arch: amd64
2022/12/31 18:09:47.510 [A] [main.go:26] Lite: false
2022/12/31 18:09:47.510 [A] [main.go:26] Version: 2.0.1
2022/12/31 18:09:47.510 [A] [main.go:26] Starting...
2022/12/31 18:09:47.510 [I] [main.go:27] the core was not running the last time v2rayA exited
2022/12/31 18:09:47.518 [A] [index.go:116] v2rayA is listening at http://127.0.0.1:2017
2022/12/31 18:09:47.518 [A] [index.go:116] v2rayA is listening at http://192.168.31.70:2017
2022/12/31 18:09:47.518 [A] [index.go:116] v2rayA is listening at http://[::1]:2017
2022/12/31 18:09:47.518 [A] [index.go:116] v2rayA is listening at http://[fe80::b68c:9dff:feb9:3827]:2017
2022/12/31 18:09:48.564 [I] [gfwlist.go:112] Downloading https://hubmirror.v2raya.org/v2rayA/dist-v2ray-rules-dat/raw/202212272209/geosite.dat to /root/.local/share/v2ray/LoyalsoldierSite.dat.new
2022/12/31 18:09:59.576 [I] [gfwlist.go:155] download[1]: https://hubmirror.v2raya.org/v2rayA/dist-v2ray-rules-dat/raw/202212272209/geosite.dat -> SUCCESS
2022/12/31 18:09:59.577 [I] [asm_amd64.s:1594] Complete updating PAC file. Localtime: 2022-12-28
2022/12/31 19:04:15.362 [A] [main.go:26] V2Ray binary is /usr/bin/v2ray
2022/12/31 19:04:15.362 [A] [main.go:26] V2Ray asset directory is /run/user/0/v2raya
2022/12/31 19:04:15.362 [A] [main.go:26] v2rayA working directory is /
2022/12/31 19:04:15.362 [A] [main.go:26] v2rayA configuration directory is /etc/v2raya
2022/12/31 19:04:15.362 [A] [main.go:26] Golang: go1.19.3
2022/12/31 19:04:15.362 [A] [main.go:26] OS: linux
2022/12/31 19:04:15.362 [A] [main.go:26] Arch: amd64
2022/12/31 19:04:15.362 [A] [main.go:26] Lite: false
2022/12/31 19:04:15.362 [A] [main.go:26] Version: 2.0.1
2022/12/31 19:04:15.362 [A] [main.go:26] Starting...
2022/12/31 19:04:15.362 [I] [main.go:27] the core was not running the last time v2rayA exited
2022/12/31 19:04:15.370 [A] [index.go:116] v2rayA is listening at http://127.0.0.1:2017
2022/12/31 19:04:15.370 [A] [index.go:116] v2rayA is listening at http://192.168.31.70:2017
2022/12/31 19:04:15.370 [A] [index.go:116] v2rayA is listening at http://[::1]:2017
2022/12/31 19:04:15.371 [A] [index.go:116] v2rayA is listening at http://[fe80::b68c:9dff:feb9:3827]:2017
2022/12/31 19:04:16.696 [W] [asm_amd64.s:1594] Failed to update PAC file: latest version is 2022-12-28. GFWList is up to date
2022/12/31 19:15:31.908 [A] [main.go:26] V2Ray binary is /usr/bin/v2ray
2022/12/31 19:15:31.908 [A] [main.go:26] V2Ray asset directory is /run/user/0/v2raya
2022/12/31 19:15:31.908 [A] [main.go:26] v2rayA working directory is /
2022/12/31 19:15:31.908 [A] [main.go:26] v2rayA configuration directory is /etc/v2raya
2022/12/31 19:15:31.908 [A] [main.go:26] Golang: go1.19.3
2022/12/31 19:15:31.908 [A] [main.go:26] OS: linux
2022/12/31 19:15:31.908 [A] [main.go:26] Arch: amd64
2022/12/31 19:15:31.908 [A] [main.go:26] Lite: false
2022/12/31 19:15:31.908 [A] [main.go:26] Version: 2.0.1
2022/12/31 19:15:31.908 [A] [main.go:26] Starting...
2022/12/31 19:15:31.908 [I] [main.go:27] the core was not running the last time v2rayA exited
2022/12/31 19:15:31.915 [A] [index.go:116] v2rayA is listening at http://127.0.0.1:2017
2022/12/31 19:15:31.915 [A] [index.go:116] v2rayA is listening at http://192.168.31.70:2017
2022/12/31 19:15:31.915 [A] [index.go:116] v2rayA is listening at http://[::1]:2017
2022/12/31 19:15:31.915 [A] [index.go:116] v2rayA is listening at http://[fe80::b68c:9dff:feb9:3827]:2017
2022/12/31 19:15:34.771 [W] [asm_amd64.s:1594] Failed to update PAC file: latest version is 2022-12-28. GFWList is up to date
2022/12/31 19:25:23.818 [A] [main.go:27] V2Ray binary is /usr/bin/v2ray
2022/12/31 19:25:23.818 [A] [main.go:27] V2Ray asset directory is /run/user/0/v2raya
2022/12/31 19:25:23.818 [A] [main.go:27] v2rayA working directory is /
2022/12/31 19:25:23.818 [A] [main.go:27] v2rayA configuration directory is /etc/v2raya
2022/12/31 19:25:23.818 [A] [main.go:27] Golang: go1.18.4
2022/12/31 19:25:23.818 [A] [main.go:27] OS: linux
2022/12/31 19:25:23.818 [A] [main.go:27] Arch: amd64
2022/12/31 19:25:23.818 [A] [main.go:27] Lite: false
2022/12/31 19:25:23.818 [A] [main.go:27] Version: 1.5.9.1698.1
2022/12/31 19:25:23.818 [A] [main.go:27] Starting...
2022/12/31 19:25:23.821 [W] [asm_amd64.s:1571] Failed to update PAC file: failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 127.0.0.53:53: server misbehaving
2022/12/31 19:25:23.827 [I] [main.go:28] the core was not running the last time v2rayA exited
2022/12/31 19:25:23.835 [W] [pre.go:272] UpdateSubscription: Get "url": dial tcp: lookup azicloud.azicloud.xyz on 127.0.0.53:53: server misbehaving: []
2022/12/31 19:25:23.835 [I] [asm_amd64.s:1571] [AutoUpdate] Subscriptions: Failed to update subscription -- ID: 0，err: UpdateSubscription: failed to resolve subscription address: Get "url": dial tcp: lookup azicloud.azicloud.xyz on 127.0.0.53:53: server misbehaving
2022/12/31 19:25:23.928 [A] [index.go:117] v2rayA is listening at http://127.0.0.1:2017
2022/12/31 19:25:23.928 [A] [index.go:117] v2rayA is listening at http://[::1]:2017
2022/12/31 19:28:41.769 [A] [main.go:26] V2Ray binary is /usr/bin/v2ray
2022/12/31 19:28:41.769 [A] [main.go:26] V2Ray asset directory is /run/user/0/v2raya
2022/12/31 19:28:41.769 [A] [main.go:26] v2rayA working directory is /
2022/12/31 19:28:41.769 [A] [main.go:26] v2rayA configuration directory is /etc/v2raya
2022/12/31 19:28:41.769 [A] [main.go:26] Golang: go1.19.3
2022/12/31 19:28:41.769 [A] [main.go:26] OS: linux
2022/12/31 19:28:41.769 [A] [main.go:26] Arch: amd64
2022/12/31 19:28:41.769 [A] [main.go:26] Lite: false
2022/12/31 19:28:41.769 [A] [main.go:26] Version: 2.0.1
2022/12/31 19:28:41.769 [A] [main.go:26] Starting...
2022/12/31 19:28:41.769 [I] [main.go:27] the core was not running the last time v2rayA exited
2022/12/31 19:28:41.772 [W] [asm_amd64.s:1594] Failed to update PAC file: failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 127.0.0.53:53: server misbehaving
2022/12/31 19:28:41.896 [A] [index.go:116] v2rayA is listening at http://127.0.0.1:2017
2022/12/31 19:28:41.896 [A] [index.go:116] v2rayA is listening at http://[::1]:2017

```

### PR DESCRIPTION
**Pull request by vzz64**
Maybe close #770. It seems that sometimes `cmd.Stdout` is written twice for two lines of output, but `onceWriter` only captures the second line of
```
V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 windows/amd64)
A unified platform for anti-censorship.
```
, so the `variant` becomes `A` which is unknown.

### CODE REVIEW

**Comment by mzz2017** [comment]
Great insight. But we need to consider that the output of v2ray in the v4 version will not stop with the same command. 

Maybe we need to wait for a maximum timeout to stop the process? What do you think?

**Comment by vzz64** [comment]
There is already one [here](https://github.com/v2rayA/v2rayA/blob/6d7069595b29ec2f57232b2f7aa90f39cc587d2c/service/core/v2ray/where/where.go#L55).

**Comment by mzz2017** [comment]
Great! Ready to merge. But I need to test if it can work with both v4 and v5 core.

I am so busy these days. Can you help me test it? Many thanks!

**Comment by vzz64** [comment]
I have tested it and both v4.45.2 and v5.1.0 work fine on Linux and Windows.

**Comment by mzz2017** [comment]
Thank you for your contribution!

**Pull request merged**
