### PR TITLE
Publish docker images on Github Container Registry

### PR DESCRIPTION
**Pull request by InvisibleRain**
This pull request aims to publish the docker images of v2rayA on ghcr.io in addition to already existing images on Docker Hub. The images are built and published using GitHub Actions every time a new v2rayA version is tagged. After the "Build & Release v2rayA" workflow completes, these images will be available under the "Packages" section of the [repository](https://github.com/v2rayA/v2rayA). After the workflow has completed, you can use this command to download the image: `docker pull ghcr.io/v2raya/v2raya:latest`

### CODE REVIEW

**Review by mzz2017 — APPROVED** [review]
LGTM.

**Comment by MarksonHon** [comment]
@InvisibleRain GitHub CI actually uses the docker files in the install/docker directory, however your pull request does not modify them. Is the new Label option is necessary for uploading Docker images to the GitHub Container Registry?

**Comment by InvisibleRain** [comment]
@MarksonHon The label is not strictly required for the GitHub Actions, but it's useful when pushing a manually built image from a personal computer.

See https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#pushing-container-images
> When you push a container image from the command line, the image is not linked to a repository by default. This is the case even if you tag the image with a namespace that matches the name of the repository, such as `ghcr.io/octocat/my-repo:latest`.
> 
> The easiest way to connect a repository to a container package is to publish the package from a workflow using `${{secrets.GITHUB_TOKEN}}`, as the repository that contains the workflow is linked automatically. Note that the `GITHUB_TOKEN` will not have permission to push the package if you have previously pushed a package to the same namespace, but have not connected the package to the repository.
>
>To connect a repository when publishing an image from the command line, and to ensure your `GITHUB_TOKEN` has appropriate permissions when using a GitHub Actions workflow, we recommend adding the label `org.opencontainers.image.source` to your `Dockerfile`. For more information, see “[Labelling container images](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#labelling-container-images)” in this article and “[Publishing and installing a package with GitHub Actions](https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions).”

**Comment by InvisibleRain** [comment]
The images are currently marked as private. I think it might be a good idea to change visibility in "Package settings"

**Comment by MarksonHon** [comment]
@InvisibleRain Done

**Pull request merged**
