### PR TITLE
add gui eslint and prettier check workflow

### PR DESCRIPTION
**Pull request by FantasqueX**
You can check last run results in my forked repository :)
Fix: #614

### CODE REVIEW

**Comment by mzz2017** [comment]
Could you please add prettier to the gui project instead of only actions?

**Comment by FantasqueX** [comment]
Sorry, I may not understand what do you mean "add prettier to the gui project". I think prettier is one of gui project devdependencies.

**Comment by mzz2017** [comment]
Alright, I did not confirm this. Maybe we can add a git hook for eslint?

**Comment by FantasqueX** [comment]
Use husky to run eslint every commit? As far as I know, many frontend projects do that. However, I don't think this PR should do that. Maybe need another PR. One PR focuses on one topic.
And I don't think we should add an eslint auto fix workflow. I think it's unreliable.

**Comment by mzz2017** [comment]
@FantasqueX Yes. Workflow just check it, not fix it. Git hook checks it and rejects the commit.

**Comment by FantasqueX** [comment]
@mzz2017 Hey, I would like to know the current status of this PR review. Any suggestions?

**Comment by mzz2017** [comment]
Would you like to add a git hook for eslint checking?

**Comment by FantasqueX** [comment]
If you insist on it, I'll try to add a husky hook.

**Comment by mzz2017** [comment]
@FantasqueX Yes, because I do not wish to push a code to remote but fail to pass CI. It should be resolved local.

**Comment by FantasqueX** [comment]
It sounds like a bootstrap problem. There are 122 errors when executing `yarn lint` and I cannot commit it since I just added a git hook😅Maybe per-requisite of this PR is to fix eslint issue

**Comment by FantasqueX** [comment]
May I ask why you close this? If all eslint issues are resolved, workflow should be added.😅

**Comment by mzz2017** [comment]
It was closed by github automatically by mistake.

**Comment by mzz2017** [comment]
Please reopen it.

**Comment by FantasqueX** [comment]
Don't know this weird feature of Github

**Comment by cubercsl** [comment]
@FantasqueX should we rebase these commits?

**Comment by FantasqueX** [comment]
There are a lot of work to do before this PR could be merged. No need to rush to rebase.

**Pull request closed without merging**
