### PR TITLE
feat: add nftables support

### PR DESCRIPTION
**Pull request by cubercsl**
Try to support nftables. 
The common features need to be tested before merging.

- [ ] tproxy
- [ ] tproxy + gateway
- [ ] tproxy + `Antipollution`
- [ ] tproxy + `Antipollution` + gateway
- [ ] tproxy + IPv4 Only
- [ ] tproxy + IPv4 Only + gateway
- [ ] redirect
- [ ] redirect + gateway
- [ ] redirect + IPv4 Only
- [ ] redirect + IPv4 Only + gateway
- [ ] **[`dropSpoofing`](https://github.com/v2rayA/v2rayA/blob/v2.0.1/service/core/iptables/dropSpoofing.go) is not yet implemented**[^1]

It is still an experimental feature and will **NOT** automatically detect the user's environment. Relevant users need to explicitly set it to use nftables via command line parameters or environment variables.
[^1]: nftables has no known method for substring matching.

### CODE REVIEW

**Comment by alphagocc** [comment]
tproxy ok

**Comment by alphagocc** [comment]
image

**Comment by cubercsl** [comment]
@alphagocc Could you provide me nft version and linux distribution and the full nft file?

**Comment by cubercsl** [comment]
@cubercsl ok i found that the comment in set elements was added in https://git.netfilter.org/nftables/commit/?id=931737a1719824d7945433177e61a6c47530ed69. Your nft may have an older version. I will fix it ASAP.

**Comment by alphagocc** [comment]
debian 11.6 nft 0.9.8

**Comment by alphagocc** [comment]
```
2023/01/23 13:09:29.598 [W] [transparent.go:47] writeTransparentProxyRules: not support "tproxy" mode of transparent proxy:
ExecCommands: nft -f /usr/local/etc/v2raya/v2raya.nft /usr/local/etc/v2raya/v2raya.nft:90:25-27: Error: syntax error, unexpected string, expecting number
tcp flags syn / fin,syn,rst,ack meta mark set mark | 0x40
^^^
: exit status 1
```

[v2raya.nft.txt](https://github.com/v2rayA/v2rayA/files/10476910/v2raya.nft.txt)

**Comment by alphagocc** [comment]
Can't access Internet(tproxy)

**Comment by alphagocc** [comment]
No log from v2raya

**Comment by cubercsl** [comment]
@alphagocc sad 😰,I don't have a spare device around to test other distributions, I will use other devices for debugging in a few days.

**Comment by alphagocc** [comment]
Hmmm, the gateway can access internet, but other devices can't

**Comment by alphagocc** [comment]
LGTM

**Comment by 1715173329** [comment]
Tested features:

- [x] tproxy
- [x] tproxy + gateway
- [x] tproxy + IPv4 Only
- [x] tproxy + IPv4 Only + gateway
- [x] redirect
- [x] redirect + gateway
- [x] redirect + IPv4 Only
- [x] redirect + IPv4 Only + gateway

.. with nftables v1.0.6 / OpenWrt SNAPSHOT d02d4556789f59

**Pull request merged**
