### PR TITLE
chore: update vue to v2.7.14

### PR DESCRIPTION
**Pull request by kecrily**
The change of `assets/` is automatically changed when `yarn serve` is running, I am not sure if this is needed, if not please let me know.

---

~~Builds under node v18 are blocked by `@achrinza/node-ipc` v9 which is a dependency of `@vue/cli-shared-utils` v4. I temporarily changed the node version used for builds from LTS (18) to 16.~~

~~I plan to work on another upgrade of `@vue/cli-*` to v5 after this PR is merged to fix this issue.~~

I decided to update it now. Because digital envelope `routines::unsupported` since node v17, https://github.com/v2rayA/v2rayA/commit/1b15508eedabf22f4d5a296b07aa1be0f9a64ad0 using `export NODE_OPTIONS=--openssl-legacy-provider` solved it.

If you switch back to node v16 then you need to revert it. It's too bad

### CODE REVIEW

**Comment by mzz2017** [comment]
> The change of assets/ is automatically changed when yarn serve is running, I am not sure if this is needed, if not please let me know.

Yes, it is automatically changed. Don't mind.

> Builds under node v18 are blocked by @achrinza/node-ipc v9 which is a dependency of @vue/cli-shared-utils v4. I temporarily changed the node version used for builds from LTS (18) to 16.

I did not confirm it. I'm fighting with covid19 these days. Maybe I'll confirm this later and figure out how to fix it.

> I plan to work on another upgrade of @vue/cli-* to v5 after this PR is merged to fix this issue.

Thanks! Looking forward to your further contribution!

**Comment by mzz2017** [comment]
Please tell me if you are ready to merge. Thanks!

**Comment by kecrily** [comment]
> Please tell me if you are ready to merge. Thanks!

It's ready to be merged, but I want to make sure everything works fine with ci.

**Comment by kecrily** [comment]
Very strange, there is no problem with the local build. But it doesn't matter, uglifyjs is deprecated, let's replace it with terser.

**Comment by mzz2017** [comment]
Everything looks fine~

**Comment by mzz2017** [comment]
Thanks for your contribution!

**Pull request merged**
