### PR TITLE
Add linux/ppc64le build

### PR DESCRIPTION
**Pull request by ChanthMiao**
Add linux/ppc64le build for release build

### CODE REVIEW

**Comment by mzz2017** [comment]
Thanks for your hard work!

**Comment by mzz2017** [comment]
Error looking at 'installer_debian_ppc64le_1.5.5.deb': 'ppc64el' is not one of the valid architectures: 'i386 amd64 armel armhf arm64 armv8'

It seems that `ppc64el` was not be supported by reprepro.

https://github.com/v2rayA/v2rayA/runs/4466781466

**Comment by mzz2017** [comment]
OK, I think I found the reason. 

https://github.com/v2rayA/v2rayA/blob/master/install/debian/conf/distributions#L5

**Comment by ChanthMiao** [comment]
> 

My mistake. I did not notice it. Good to know you that you already fixed it.

**Pull request merged**
